all:
  hosts:
    another-test:
      ansible_host: '12312'
      host_agent_url: http://12312:8001
      status: pending
      last_seen_epoch: 1764881210
      dut_list: {}
      openocd_cfg: /etc/openocd/boards/cc26x2.cfg
